# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/DATA/2024/sem07/SEP/SEP_projects/memorice/memorice.srcs/sources_1/bd/design_1/ip/design_1_ram_reader_0_0/design_1_ram_reader_0_0.xci
# IP: The module: 'design_1_ram_reader_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/DATA/2024/sem07/SEP/SEP_projects/memorice/memorice.srcs/sources_1/bd/design_1/ip/design_1_ram_reader_0_0/ip/levels/levels.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==levels || ORIG_REF_NAME==levels} -quiet] -quiet

# XDC: c:/DATA/2024/sem07/SEP/SEP_projects/memorice/memorice.srcs/sources_1/bd/design_1/ip/design_1_ram_reader_0_0/ip/levels/levels_ooc.xdc

# IP: C:/DATA/2024/sem07/SEP/SEP_projects/memorice/memorice.srcs/sources_1/bd/design_1/ip/design_1_ram_reader_0_0/design_1_ram_reader_0_0.xci
# IP: The module: 'design_1_ram_reader_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/DATA/2024/sem07/SEP/SEP_projects/memorice/memorice.srcs/sources_1/bd/design_1/ip/design_1_ram_reader_0_0/ip/levels/levels.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==levels || ORIG_REF_NAME==levels} -quiet] -quiet

# XDC: c:/DATA/2024/sem07/SEP/SEP_projects/memorice/memorice.srcs/sources_1/bd/design_1/ip/design_1_ram_reader_0_0/ip/levels/levels_ooc.xdc
