# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/DATA/2024/sem07/SEP/SEP_projects/Zybo-Z7-Master.xdc

# Block Designs: bd/design_1/design_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_Init_0_0/design_1_Init_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_Init_0_0 || ORIG_REF_NAME==design_1_Init_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ID_selector_0_0/design_1_ID_selector_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_ID_selector_0_0 || ORIG_REF_NAME==design_1_ID_selector_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ram_reader_0_0/design_1_ram_reader_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_ram_reader_0_0 || ORIG_REF_NAME==design_1_ram_reader_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_state_machine_0_0/design_1_state_machine_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_state_machine_0_0 || ORIG_REF_NAME==design_1_state_machine_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_state_wait_0_0/design_1_state_wait_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_state_wait_0_0 || ORIG_REF_NAME==design_1_state_wait_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_state_results_0_0/design_1_state_results_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_state_results_0_0 || ORIG_REF_NAME==design_1_state_results_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_Game_0_0/design_1_Game_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_Game_0_0 || ORIG_REF_NAME==design_1_Game_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_LightController_0_0/design_1_LightController_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_LightController_0_0 || ORIG_REF_NAME==design_1_LightController_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_vio_0_1/design_1_vio_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_vio_0_1 || ORIG_REF_NAME==design_1_vio_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_0_0 || ORIG_REF_NAME==design_1_clk_wiz_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_proc_sys_reset_0_0/design_1_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_proc_sys_reset_0_0 || ORIG_REF_NAME==design_1_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_traffic_gen_0_0/design_1_axi_traffic_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_traffic_gen_0_0 || ORIG_REF_NAME==design_1_axi_traffic_gen_0_0} -quiet] -quiet

# XDC: bd/design_1/design_1_ooc.xdc
