# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/gusta/Documents/SEP_projects/Zybo-Z7-Master.xdc

# Block Designs: bd/design_1/design_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_LedShow_0_0/design_1_LedShow_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_LedShow_0_0 || ORIG_REF_NAME==design_1_LedShow_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ram_reader_0_0/design_1_ram_reader_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_ram_reader_0_0 || ORIG_REF_NAME==design_1_ram_reader_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ID_selector_0_0/design_1_ID_selector_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_ID_selector_0_0 || ORIG_REF_NAME==design_1_ID_selector_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_SM_0_0/design_1_SM_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_SM_0_0 || ORIG_REF_NAME==design_1_SM_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_state_init_0_0/design_1_state_init_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_state_init_0_0 || ORIG_REF_NAME==design_1_state_init_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_state_wait_0_0/design_1_state_wait_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_state_wait_0_0 || ORIG_REF_NAME==design_1_state_wait_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_state_results_0_0/design_1_state_results_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_state_results_0_0 || ORIG_REF_NAME==design_1_state_results_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_Comparer_0_0/design_1_Comparer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_Comparer_0_0 || ORIG_REF_NAME==design_1_Comparer_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_driver_0_0/design_1_driver_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_driver_0_0 || ORIG_REF_NAME==design_1_driver_0_0} -quiet] -quiet

# XDC: bd/design_1/design_1_ooc.xdc
