# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/DATA/2024/sem07/SEP/SEP_projects/memorice/memorice.srcs/sources_1/bd/design_1/ip/design_1_Game_0_0/design_1_Game_0_0.xci
# IP: The module: 'design_1_Game_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/DATA/2024/sem07/SEP/SEP_projects/memorice/memorice.srcs/sources_1/bd/design_1/ip/design_1_Game_0_0/constrs_1/new/Zybo-Z7-Master.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_Game_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/DATA/2024/sem07/SEP/SEP_projects/memorice/memorice.srcs/sources_1/bd/design_1/ip/design_1_Game_0_0/design_1_Game_0_0.xci
# IP: The module: 'design_1_Game_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/DATA/2024/sem07/SEP/SEP_projects/memorice/memorice.srcs/sources_1/bd/design_1/ip/design_1_Game_0_0/constrs_1/new/Zybo-Z7-Master.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_Game_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
