# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/DATA/2024/7mo semestre/SEP/Proyectos/ram_reader/ram_reader.srcs/sources_1/ip/levels/levels.xci
# IP: The module: 'levels' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/DATA/2024/7mo semestre/SEP/Proyectos/ram_reader/ram_reader.srcs/sources_1/ip/levels/levels_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'levels'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/DATA/2024/7mo semestre/SEP/Proyectos/ram_reader/ram_reader.srcs/sources_1/ip/levels/levels.xci
# IP: The module: 'levels' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/DATA/2024/7mo semestre/SEP/Proyectos/ram_reader/ram_reader.srcs/sources_1/ip/levels/levels_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'levels'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
