# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/gusta/OneDrive/Documents/universidad/4to/1r/SEP/Proyectos/pr2/SEPmonG3/SEPmon/SEPmon.srcs/sources_1/bd/DEMO/ip/DEMO_axi_iic_0_1/DEMO_axi_iic_0_1.xci
# IP: The module: 'DEMO_axi_iic_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/gusta/OneDrive/Documents/universidad/4to/1r/SEP/Proyectos/pr2/SEPmonG3/SEPmon/SEPmon.srcs/sources_1/bd/DEMO/ip/DEMO_axi_iic_0_1/DEMO_axi_iic_0_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'DEMO_axi_iic_0_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/gusta/OneDrive/Documents/universidad/4to/1r/SEP/Proyectos/pr2/SEPmonG3/SEPmon/SEPmon.srcs/sources_1/bd/DEMO/ip/DEMO_axi_iic_0_1/DEMO_axi_iic_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DEMO_axi_iic_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/gusta/OneDrive/Documents/universidad/4to/1r/SEP/Proyectos/pr2/SEPmonG3/SEPmon/SEPmon.srcs/sources_1/bd/DEMO/ip/DEMO_axi_iic_0_1/DEMO_axi_iic_0_1.xci
# IP: The module: 'DEMO_axi_iic_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/gusta/OneDrive/Documents/universidad/4to/1r/SEP/Proyectos/pr2/SEPmonG3/SEPmon/SEPmon.srcs/sources_1/bd/DEMO/ip/DEMO_axi_iic_0_1/DEMO_axi_iic_0_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'DEMO_axi_iic_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/gusta/OneDrive/Documents/universidad/4to/1r/SEP/Proyectos/pr2/SEPmonG3/SEPmon/SEPmon.srcs/sources_1/bd/DEMO/ip/DEMO_axi_iic_0_1/DEMO_axi_iic_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DEMO_axi_iic_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
