# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/gusta/OneDrive/Documents/universidad/4to/1r/SEP/Proyectos/pr2/SEPmonG3/SEPmon/SEPmon.srcs/sources_1/bd/DEMO/ip/DEMO_xbar_0/DEMO_xbar_0.xci
# IP: The module: 'DEMO_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/gusta/OneDrive/Documents/universidad/4to/1r/SEP/Proyectos/pr2/SEPmonG3/SEPmon/SEPmon.srcs/sources_1/bd/DEMO/ip/DEMO_xbar_0/DEMO_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DEMO_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: C:/Users/gusta/OneDrive/Documents/universidad/4to/1r/SEP/Proyectos/pr2/SEPmonG3/SEPmon/SEPmon.srcs/sources_1/bd/DEMO/ip/DEMO_xbar_0/DEMO_xbar_0.xci
# IP: The module: 'DEMO_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/gusta/OneDrive/Documents/universidad/4to/1r/SEP/Proyectos/pr2/SEPmonG3/SEPmon/SEPmon.srcs/sources_1/bd/DEMO/ip/DEMO_xbar_0/DEMO_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DEMO_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
